(function(){
    var modules={
        "panel-main-osa-clean":    	        {url:"$H/m/panel-main.html",router:1},
        "panel-child-osa-clean":              {url:"$H/m/panel-child.html"},
        "panel-setup-osa-clean":              {url:"$H/m/panel-setup.html"},
        "panel-library-osa-clean":    		{url:"$H/m/panel-library.html",router:1},
        "panel-export-screening-osa-clean":   {url:"$H/m/export/panel-export-screened.html",router:1},
        "panel-export-enrolled-osa-clean":    {url:"$H/m/export/panel-export-enrolled.html",router:1},
        "export-data":		                {url:"$H/m/export/export-data.html",Table:"export-osa-clean",form_module:"export-form"},
        "export-form":		                {url:"$H/m/export/export-form.html",Table:"export-osa-clean"},
        
        "participant-data":   		        {url:"$H/m/participant/participant-data.html",Table:"participant-osa-clean",form_module:"participant-form",router:1,
                                                child_panel:"panel-child-osa-clean",
                                                questionnaire_setup:"online-questionnaire-setup-osa-clean",
                                                online_questionnaire:"online-questionnaire-app-osa-clean",
                                                participant_id:{field1:"Subject_ID",field2:"Subject_Initials"},
                                                participant_export:"ID,Subject_ID,Screening_Number,Randomisation_Number,Subject_Initials,Gender,DOB",
                                                Table2:"site-permission-osa-clean",
                                                Table3:"site-osa-clean",                                                
                                            },
       "participant-form":   		        {url:"$H/m/participant/participant-form.html",Table:"participant-osa-clean",Table2:"site-permission-osa-clean",Table3:"site-osa-clean"},

        "online-questionnaire-setup-osa-clean": {url:"$H/m/oq-setup.html",Table:"participant-osa-clean"},
        "online-questionnaire-app-osa-clean":   {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"notes-osa-clean",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"notes-osa-clean"},

        "history-data":  	                    {url:"$H/m/library/history-data.html",form_module:"history-form",task_name:"History Data"},
        "history-form":  	                    {url:"$H/m/library/history-form.html"},

        "site-data-osa-clean":  	            {url:"$H/m/library/site-data.html",Table:"site-osa-clean",form_module:"site-form-osa-clean",task_name:"Site List",router:1},
        "site-form-osa-clean":  	            {url:"$H/m/library/site-form.html",Table:"site-osa-clean",task_name:"Site List"},
        "site-permission-data-osa-clean":  	{url:"$H/m/library/site-permission-data.html",Table:"site-permission-osa-clean",form_module:"site-permission-form-osa-clean",task_name:"Site Permission List",router:1},
        "site-permission-form-osa-clean":  	{url:"$H/m/library/site-permission-form.html",Table:"site-permission-osa-clean",task_name:"Site Permission List"},


        "randomisation-table-sydney-50-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-sydney-50-osa-clean",form_module:"randomisation-table-sydney-50-form-osa-clean"},
        "randomisation-table-sydney-50-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-sydney-50-osa-clean"},
        "randomisation-table-macquarie-50-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-macquarie-50-osa-clean",form_module:"randomisation-table-macquarie-50-form-osa-clean"},
        "randomisation-table-macquarie-50-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-macquarie-50-osa-clean"},
        "randomisation-table-austin-50-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-austin-50-osa-clean",form_module:"randomisation-table-austin-50-form-osa-clean"},
        "randomisation-table-austin-50-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-austin-50-osa-clean"},
        "randomisation-table-tasmania-50-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-tasmania-50-osa-clean",form_module:"randomisation-table-tasmania-50-form-osa-clean"},
        "randomisation-table-tasmania-50-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-tasmania-50-osa-clean"},
        "randomisation-table-murdoch-50-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-murdoch-50-osa-clean",form_module:"randomisation-table-murdoch-50-form-osa-clean"},
        "randomisation-table-murdoch-50-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-murdoch-50-osa-clean"},
        "randomisation-table-sydney-65-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-sydney-65-osa-clean",form_module:"randomisation-table-sydney-65-form-osa-clean"},
        "randomisation-table-sydney-65-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-sydney-65-osa-clean"},
        "randomisation-table-macquarie-65-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-macquarie-65-osa-clean",form_module:"randomisation-table-macquarie-65-form-osa-clean"},
        "randomisation-table-macquarie-65-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-macquarie-65-osa-clean"},
        "randomisation-table-austin-65-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-austin-65-osa-clean",form_module:"randomisation-table-austin-65-form-osa-clean"},
        "randomisation-table-austin-65-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-austin-65-osa-clean"},
        "randomisation-table-tasmania-65-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-tasmania-65-osa-clean",form_module:"randomisation-table-tasmania-65-form-osa-clean"},
        "randomisation-table-tasmania-65-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-tasmania-65-osa-clean"},
        "randomisation-table-murdoch-65-data-osa-clean":		{url:"$H/m/library/randomisation-table-data.html",Table:"randomisation-table-murdoch-65-osa-clean",form_module:"randomisation-table-murdoch-65-form-osa-clean"},
        "randomisation-table-murdoch-65-form-osa-clean":		{url:"$H/m/library/randomisation-table-form.html",Table:"randomisation-table-murdoch-65-osa-clean"},

        "adverse-event-data-osa-clean":		{url:"$H/m/library/adverse-event-data.html",Table:"adverse-event-osa-clean",form_module:"adverse-event-form-osa-clean",task_name:"Unscheduled - Adverse Event"},
        "adverse-event-form-osa-clean":		{url:"$H/m/library/adverse-event-form.html",Table:"adverse-event-osa-clean",task_name:"Unscheduled -  Adverse Event"},
        "withdrawal-data-osa-clean":		{url:"$H/m/library/withdrawal-data.html",Table:"withdrawal-osa-clean",form_module:"withdrawal-form-osa-clean",task_name:"Unscheduled - Withdrawal"},
        "withdrawal-form-osa-clean":		{url:"$H/m/library/withdrawal-form.html",Table:"withdrawal-osa-clean",task_name:"Unscheduled - Withdrawal"},
        "pre-withdrawal-data-osa-clean":		{url:"$H/m/library/pre-withdrawal-data.html",Table:"pre-withdrawal-osa-clean",Table2:"site-permission-osa-clean",form_module:"pre-withdrawal-form-osa-clean",task_name:"Unscheduled - Pre Study Withdrawal"},
        "pre-withdrawal-form-osa-clean":		{url:"$H/m/library/pre-withdrawal-form.html",Table:"pre-withdrawal-osa-clean",task_name:"Unscheduled - Pre Study Withdrawal"},
        "concom-medication-data-osa-clean":		{url:"$H/m/library/concom-medication-data.html",Table:"concom-medication-osa-clean",form_module:"concom-medication-form-osa-clean",task_name:"Unscheduled - Concomitant Medication"},
        "concom-medication-form-osa-clean":		{url:"$H/m/library/concom-medication-form.html",Table:"concom-medication-osa-clean",task_name:"Unscheduled - Concomitant Medication"},
        "file-notes-data-osa-clean":		{url:"$H/m/library/file-notes-data.html",Table:"file-notes-osa-clean",form_module:"file-notes-form-osa-clean",task_name:"Unscheduled - File Notes"},
        "file-notes-form-osa-clean":		{url:"$H/m/library/file-notes-form.html",Table:"file-notes-osa-clean",task_name:"Unscheduled - File Notes"},
        "consent-ps-data-osa-clean":		        {url:"$H/m/library/consent-date-data.html",Table:"consent-ps-osa-clean",form_module:"consent-ps-form-osa-clean",task_name:"Pre-screening - Date of Sign Consent"},
        "consent-ps-form-osa-clean":		        {url:"$H/m/library/consent-date-form.html",Table:"consent-ps-osa-clean",task_name:"Pre-screening - Date of Sign Consent"},
        "date-ps-data-osa-clean":                {url:"$H/m/library/date-data.html",Table:"date-ps-osa-clean",form_module:"date-ps-form-osa-clean",task_name:"Pre-screening - Visit Date"},
        "date-ps-form-osa-clean":                {url:"$H/m/library/date-form.html",Table:"date-ps-osa-clean",task_name:"Pre-screening - Visit Date"},
        "wristox-ps-data-osa-clean":	    {url:"$H/m/library/wristox-v2-data.html",Table:"wristox-ps-osa-clean",form_module:"wristox-ps-form-osa-clean",task_name:"Pre-screening - Wristox"},
        "wristox-ps-form-osa-clean":	    {url:"$H/m/library/wristox-v2-form.html",Table:"wristox-ps-osa-clean",task_name:"Pre-screening - Wristox"},
        "demographics-ps-data-osa-clean":	    {url:"$H/m/library/demographics-data.html",Table:"demographics-ps-osa-clean",form_module:"demographics-ps-form-osa-clean",task_name:"Pre-screening - Demographics"},
        "demographics-ps-form-osa-clean":	    {url:"$H/m/library/demographics-form.html",Table:"demographics-ps-osa-clean",task_name:"Pre-screening - Demographics"},
        "eligibility-ps-data-osa-clean":	    {url:"$H/m/library/eligibility-data.html",Table:"eligibility-ps-osa-clean",form_module:"eligibility-ps-form-osa-clean",task_name:"Pre-screening - Eligibility"},
        "eligibility-ps-form-osa-clean":	    {url:"$H/m/library/eligibility-form.html",Table:"eligibility-ps-osa-clean",task_name:"Pre-screening - Eligibility",router:1},

        "date-s-data-osa-clean":                {url:"$H/m/library/date-data.html",Table:"date-s-osa-clean",form_module:"date-s-form-osa-clean",task_name:"Screening - Visit Date"},
        "date-s-form-osa-clean":                {url:"$H/m/library/date-form.html",Table:"date-s-osa-clean",task_name:"Screening - Visit Date"},
        "consent-s-data-osa-clean":		        {url:"$H/m/library/consent-s-date-data.html",Table:"consent-s-osa-clean",form_module:"consent-s-form-osa-clean",task_name:"Screening - Date of Sign Consent"},
        "consent-s-form-osa-clean":		        {url:"$H/m/library/consent-s-date-form.html",Table:"consent-s-osa-clean",task_name:"Screening - Date of Sign Consent"},
        "consent-mri-data-osa-clean":		        {url:"$H/m/library/consent-mri-data.html",Table:"consent-mri-osa-clean",form_module:"consent-mri-form-osa-clean",task_name:"Screening - MRI Date of Sign Consent"},
        "consent-mri-form-osa-clean":		        {url:"$H/m/library/consent-mri-form.html",Table:"consent-mri-osa-clean",task_name:"Screening - MRI Date of Sign Consent"},
        "demographics-s-data-osa-clean":	    {url:"$H/m/library/demographics-long-data.html",Table:"demographics-s-osa-clean",form_module:"demographics-s-form-osa-clean",task_name:"Screening - Demographics"},
        "demographics-s-form-osa-clean":	    {url:"$H/m/library/demographics-long-form.html",Table:"demographics-s-osa-clean",task_name:"Screening - Demographics"},
        "medical-assessment-s-data-osa-clean":	    {url:"$H/m/library/medical-assessment-data.html",Table:"medical-assessment-s-osa-clean",form_module:"medical-assessment-s-form-osa-clean",task_name:"Screening - Medical History"},
        "medical-assessment-s-form-osa-clean":	    {url:"$H/m/library/medical-assessment-form.html",Table:"medical-assessment-s-osa-clean",task_name:"Screening - Medical History"},
        "medical-predef-s-data-osa-clean":	    {url:"$H/m/library/medical-predef-data.html",Table:"medical-predef-s-osa-clean",form_module:"medical-predef-s-form-osa-clean",task_name:"Screening - Medical History Predefined Conditions"},
        "medical-predef-s-form-osa-clean":	    {url:"$H/m/library/medical-predef-form.html",Table:"medical-predef-s-osa-clean",task_name:"Screening - Medical History Predefined Conditions"},
        "biomedical-measurements-s-data-osa-clean":{url:"$H/m/library/biomedical-measurements-data.html",Table:"biomedical-measurements-s-osa-clean",form_module:"biomedical-measurements-s-form-osa-clean",task_name:"Screening - Biomedical Measurements"},
        "biomedical-measurements-s-form-osa-clean":{url:"$H/m/library/biomedical-measurements-form.html",Table:"biomedical-measurements-s-osa-clean",task_name:"Screening - Biomedical Measurements"},
        "in-ex-s-data-osa-clean":	            {url:"$H/m/library/inclusion-exclusion-data.html",Table:"in-ex-s-osa-clean",form_module:"in-ex-s-form-osa-clean",task_name:"Screening - Inclusion/ Exclusion Criteria"},
        "in-ex-s-form-osa-clean":	            {url:"$H/m/library/inclusion-exclusion-form.html",Table:"in-ex-s-osa-clean",task_name:"Screening - Inclusion/ Exclusion Criteria"},

        "date-bl-data-osa-clean":                {url:"$H/m/library/date-data.html",Table:"date-bl-osa-clean",form_module:"date-bl-form-osa-clean",task_name:"Baseline - Visit Date"},
        "date-bl-form-osa-clean":                {url:"$H/m/library/date-form.html",Table:"date-bl-osa-clean",task_name:"Baseline - Visit Date"},
        "btb-bl-data-osa-clean":                {url:"$H/m/library/btb-data.html",Table:"btb-bl-osa-clean",form_module:"btb-bl-form-osa-clean",task_name:"Baseline - Blood Test"},
        "btb-bl-form-osa-clean":                {url:"$H/m/library/btb-form.html",Table:"btb-bl-osa-clean",task_name:"Baseline - Blood Test"},
        "watchpat-bl-data-osa-clean":                {url:"$H/m/library/watchpat-data.html",Table:"watchpat-bl-osa-clean",form_module:"watchpat-bl-form-osa-clean",task_name:"Baseline - WatchPat"},
        "watchpat-bl-form-osa-clean":                {url:"$H/m/library/watchpat-form.html",Table:"watchpat-bl-osa-clean",task_name:"Baseline - WatchPat"},
        "mri-bl-data-osa-clean":                {url:"$H/m/library/mri-data.html",Table:"mri-bl-osa-clean",form_module:"mri-bl-form-osa-clean",task_name:"Baseline - MRI data"},
        "mri-bl-form-osa-clean":                {url:"$H/m/library/mri-form.html",Table:"mri-bl-osa-clean",task_name:"Baseline - MRI data"},
        "pet-bl-data-osa-clean":                {url:"$H/m/library/pet-data.html",Table:"pet-bl-osa-clean",form_module:"pet-bl-form-osa-clean",task_name:"Baseline - PET data"},
        "pet-bl-form-osa-clean":                {url:"$H/m/library/pet-form.html",Table:"pet-bl-osa-clean",task_name:"Baseline - PET data"},
        "biomedical-measurements-bl-data-osa-clean":                {url:"$H/m/library/biomedical-measurements-data.html",Table:"biomedical-measurements-bl-osa-clean",form_module:"biomedical-measurements-bl-form-osa-clean",task_name:"Baseline - Biomedical Measurements"},
        "biomedical-measurements-bl-form-osa-clean":                {url:"$H/m/library/biomedical-measurements-form.html",Table:"biomedical-measurements-bl-osa-clean",task_name:"Baseline - Biomedical Measurements"},
        "stop-bang-bl-data-osa-clean":                {url:"$H/m/library/stop-bang-data.html",Table:"stop-bang-bl-osa-clean",form_module:"stop-bang-bl-form-osa-clean",task_name:"Baseline - STOP BANG"},
        "stop-bang-bl-form-osa-clean":                {url:"$H/m/library/stop-bang-form.html",Table:"stop-bang-bl-osa-clean",task_name:"Baseline - STOP BANG"},
        "cirs-bl-data-osa-clean":                {url:"$H/m/library/cirs-data.html",Table:"cirs-bl-osa-clean",form_module:"cirs-bl-form-osa-clean",task_name:"Baseline - Cumulative Illness Rating Scale"},
        "cirs-bl-form-osa-clean":                {url:"$H/m/library/cirs-form.html",Table:"cirs-bl-osa-clean",task_name:"Baseline - Cumulative Illness Rating Scale"},
        "ravlt-7-bl-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-bl-osa-clean",form_module:"ravlt-7-bl-form-osa-clean",task_name:"Baseline - RAVLT Trials"},
        "ravlt-7-bl-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-bl-osa-clean",task_name:"Baseline - RAVLT Trials"},
        "trail-part-b-bl-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-bl-osa-clean",form_module:"trail-part-b-bl-form-osa-clean",task_name:"Baseline - Trail Making Test Part A and B"},
        "trail-part-b-bl-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-bl-osa-clean",task_name:"Baseline - Trail Making Test Part A and B"},
        "dkefs-bl-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-bl-osa-clean",form_module:"dkefs-bl-form-osa-clean",task_name:"Baseline - Delis Kaplan Executive Functioning System"},
        "dkefs-bl-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-bl-osa-clean",task_name:"Baseline - Delis Kaplan Executive Functioning System"},
        "sdmt-bl-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-bl-osa-clean",form_module:"sdmt-bl-form-osa-clean",task_name:"Baseline - Symbol Digit Modalities Test"},
        "sdmt-bl-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-bl-osa-clean",task_name:"Baseline - Symbol Digit Modalities Test"},
        "cantab-bl-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-bl-osa-clean",form_module:"cantab-bl-form-osa-clean",task_name:"Baseline - CANTAB"},
        "cantab-bl-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-bl-osa-clean",task_name:"Baseline - CANTAB"},
        "ravlt-7-de-bl-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-de-bl-osa-clean",form_module:"ravlt-7-de-bl-form-osa-clean",task_name:"Baseline - Double Entry - RAVLT Trials"},
        "ravlt-7-de-bl-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-de-bl-osa-clean",task_name:"Baseline - Double Entry - RAVLT Trials"},
        "trail-part-b-de-bl-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-de-bl-osa-clean",form_module:"trail-part-b-de-bl-form-osa-clean",task_name:"Baseline - Double Entry - Trail Making Test Part A and B"},
        "trail-part-b-de-bl-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-de-bl-osa-clean",task_name:"Baseline - Double Entry - Trail Making Test Part A and B"},
        "dkefs-de-bl-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-de-bl-osa-clean",form_module:"dkefs-de-bl-form-osa-clean",task_name:"Baseline - Double Entry - Delis Kaplan Executive Functioning System"},
        "dkefs-de-bl-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-de-bl-osa-clean",task_name:"Baseline - Double Entry - Delis Kaplan Executive Functioning System"},
        "sdmt-de-bl-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-de-bl-osa-clean",form_module:"sdmt-de-bl-form-osa-clean",task_name:"Baseline - Double Entry - Symbol Digit Modalities Test"},
        "sdmt-de-bl-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-de-bl-osa-clean",task_name:"Baseline - Double Entry - Symbol Digit Modalities Test"},
        "cantab-de-bl-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-de-bl-osa-clean",form_module:"cantab-de-bl-form-osa-clean",task_name:"Baseline - Double Entry - CANTAB"},
        "cantab-de-bl-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-de-bl-osa-clean",task_name:"Baseline - Double Entry - CANTAB"},
        "gad-7-bl-data-osa-clean":                {url:"$H/m/library/gad7-data.html",Table:"gad-7-bl-osa-clean",form_module:"gad-7-bl-form-osa-clean",task_name:"Baseline - Generalised Anxiety Disorder – 7 (GAD-7)"},
        "gad-7-bl-form-osa-clean":                {url:"$H/m/library/gad7-form.html",Table:"gad-7-bl-osa-clean",task_name:"Baseline - Generalised Anxiety Disorder – 7 (GAD-7)"},
        "psqi-bl-data-osa-clean":                {url:"$H/m/library/psqi-data.html",Table:"psqi-bl-osa-clean",form_module:"psqi-bl-form-osa-clean",task_name:"Baseline - The Pittsburgh Sleep Quality Index (PSQI)"},
        "psqi-bl-form-osa-clean":                {url:"$H/m/library/psqi-form.html",Table:"psqi-bl-osa-clean",task_name:"Baseline - The Pittsburgh Sleep Quality Index (PSQI)"},
        "audit-part-bl-data-osa-clean":                {url:"$H/m/library/audit-part-data.html",Table:"audit-part-bl-osa-clean",form_module:"audit-part-bl-form-osa-clean",task_name:"Baseline - Alcohol Use Disorders Identification Test (Audit)"},
        "audit-part-bl-form-osa-clean":                {url:"$H/m/library/audit-part-form.html",Table:"audit-part-bl-osa-clean",task_name:"Baseline - Alcohol Use Disorders Identification Test (Audit)"},
        "phq-9-bl-data-osa-clean":                {url:"$H/m/library/phq-data.html",Table:"phq-9-bl-osa-clean",form_module:"phq-9-bl-form-osa-clean",task_name:"Baseline - The Patient Health Questionnaire-9 (PHQ-9)"},
        "phq-9-bl-form-osa-clean":                {url:"$H/m/library/phq-form.html",Table:"phq-9-bl-osa-clean",task_name:"Baseline - The Patient Health Questionnaire-9 (PHQ-9)"},
        "bc-cci-bl-data-osa-clean":                {url:"$H/m/library/bc-cci-data.html",Table:"bc-cci-bl-osa-clean",form_module:"bc-cci-bl-form-osa-clean",task_name:"Baseline - Brittish Colombia Cognitive Complaints Inventory"},
        "bc-cci-bl-form-osa-clean":                {url:"$H/m/library/bc-cci-form.html",Table:"bc-cci-bl-osa-clean",task_name:"Baseline - Brittish Colombia Cognitive Complaints Inventory"},
        "eq-5d-bl-data-osa-clean":                {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-bl-osa-clean",form_module:"eq-5d-bl-form-osa-clean",task_name:"Baseline - Quality of life inventory (EQ-5D-5L)"},
        "eq-5d-bl-form-osa-clean":                {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-bl-osa-clean",task_name:"Baseline - Quality of life inventory (EQ-5D-5L)"},
        "ess-bl-data-osa-clean":                {url:"$H/m/library/ess-data.html",Table:"ess-bl-osa-clean",form_module:"ess-bl-form-osa-clean",task_name:"Baseline - Epworth Sleepiness Scale (ESS)"},
        "ess-bl-form-osa-clean":                {url:"$H/m/library/ess-form.html",Table:"ess-bl-osa-clean",task_name:"Baseline - Epworth Sleepiness Scale (ESS)"},

        "date-6-data-osa-clean":                {url:"$H/m/library/date-data.html",Table:"date-6-osa-clean",form_module:"date-6-form-osa-clean",task_name:"6 Months - Visit Date"},
        "date-6-form-osa-clean":                {url:"$H/m/library/date-form.html",Table:"date-6-osa-clean",task_name:"6 Months - Visit Date"},
        "btb-6-data-osa-clean":                {url:"$H/m/library/btb-data.html",Table:"btb-6-osa-clean",form_module:"btb-6-form-osa-clean",task_name:"6 Months - Blood Test"},
        "btb-6-form-osa-clean":                {url:"$H/m/library/btb-form.html",Table:"btb-6-osa-clean",task_name:"6 Months - Blood Test"},
        "watchpat-6-data-osa-clean":                {url:"$H/m/library/watchpat-data.html",Table:"watchpat-6-osa-clean",form_module:"watchpat-6-form-osa-clean",task_name:"6 Months - WatchPat"},
        "watchpat-6-form-osa-clean":                {url:"$H/m/library/watchpat-form.html",Table:"watchpat-6-osa-clean",task_name:"6 Months - WatchPat"},
        "biomedical-measurements-6-data-osa-clean":                {url:"$H/m/library/biomedical-measurements-6-data.html",Table:"biomedical-measurements-6-osa-clean",form_module:"biomedical-measurements-6-form-osa-clean",task_name:"6 Months - Biomedical Measurements"},
        "biomedical-measurements-6-form-osa-clean":                {url:"$H/m/library/biomedical-measurements-6-form.html",Table:"biomedical-measurements-6-osa-clean",task_name:"6 Months  - Biomedical Measurements"},
        "ravlt-7-6-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-6-osa-clean",form_module:"ravlt-7-6-form-osa-clean",task_name:"6 Months - RAVLT Trials"},
        "ravlt-7-6-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-6-osa-clean",task_name:"6 Months - RAVLT Trials"},
        "trail-part-b-6-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-6-osa-clean",form_module:"trail-part-b-6-form-osa-clean",task_name:"6 Months - Trail Making Test Part A and B"},
        "trail-part-b-6-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-6-osa-clean",task_name:"6 Months - Trail Making Test Part A and B"},
        "dkefs-6-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-6-osa-clean",form_module:"dkefs-6-form-osa-clean",task_name:"6 Months - Delis Kaplan Executive Functioning System"},
        "dkefs-6-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-6-osa-clean",task_name:"6 Months - Delis Kaplan Executive Functioning System"},
        "sdmt-6-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-6-osa-clean",form_module:"sdmt-6-form-osa-clean",task_name:"6 Months - Symbol Digit Modalities Test"},
        "sdmt-6-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-6-osa-clean",task_name:"6 Months - Symbol Digit Modalities Test"},
        "cantab-6-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-6-osa-clean",form_module:"cantab-6-form-osa-clean",task_name:"6 Months - CANTAB"},
        "cantab-6-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-6-osa-clean",task_name:"6 Months - CANTAB"},
        "ravlt-7-de-6-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-de-6-osa-clean",form_module:"ravlt-7-de-6-form-osa-clean",task_name:"6 Months - Double Entry - RAVLT Trials"},
        "ravlt-7-de-6-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-de-6-osa-clean",task_name:"6 Months - Double Entry - RAVLT Trials"},
        "trail-part-b-de-6-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-de-6-osa-clean",form_module:"trail-part-b-de-6-form-osa-clean",task_name:"6 Months - Double Entry - Trail Making Test Part A and B"},
        "trail-part-b-de-6-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-de-6-osa-clean",task_name:"6 Months - Double Entry - Trail Making Test Part A and B"},
        "dkefs-de-6-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-de-6-osa-clean",form_module:"dkefs-de-6-form-osa-clean",task_name:"6 Months - Double Entry - Delis Kaplan Executive Functioning System"},
        "dkefs-de-6-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-de-6-osa-clean",task_name:"6 Months - Double Entry - Delis Kaplan Executive Functioning System"},
        "sdmt-de-6-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-de-6-osa-clean",form_module:"sdmt-de-6-form-osa-clean",task_name:"6 Months - Double Entry - Symbol Digit Modalities Test"},
        "sdmt-de-6-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-de-6-osa-clean",task_name:"6 Months - Double Entry - Symbol Digit Modalities Test"},
        "cantab-de-6-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-de-6-osa-clean",form_module:"cantab-de-6-form-osa-clean",task_name:"6 Months - Double Entry - CANTAB"},
        "cantab-de-6-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-de-6-osa-clean",task_name:"6 Months - Double Entry - CANTAB"},
        "phq-9-6-data-osa-clean":                {url:"$H/m/library/phq-data.html",Table:"phq-9-6-osa-clean",form_module:"phq-9-6-form-osa-clean",task_name:"6 Months - The Patient Health Questionnaire-9 (PHQ-9)"},
        "phq-9-6-form-osa-clean":                {url:"$H/m/library/phq-form.html",Table:"phq-9-6-osa-clean",task_name:"6 Months - The Patient Health Questionnaire-9 (PHQ-9)"},
        "bc-cci-6-data-osa-clean":                {url:"$H/m/library/bc-cci-data.html",Table:"bc-cci-6-osa-clean",form_module:"bc-cci-6-form-osa-clean",task_name:"6 Months - Brittish Colombia Cognitive Complaints Inventory"},
        "bc-cci-6-form-osa-clean":                {url:"$H/m/library/bc-cci-form.html",Table:"bc-cci-6-osa-clean",task_name:"6 Months - Brittish Colombia Cognitive Complaints Inventory"},
        "eq-5d-6-data-osa-clean":                {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-6-osa-clean",form_module:"eq-5d-6-form-osa-clean",task_name:"6 Months - Quality of life inventory (EQ-5D-5L)"},
        "eq-5d-6-form-osa-clean":                {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-6-osa-clean",task_name:"6 Months - Quality of life inventory (EQ-5D-5L)"},
        "ess-6-data-osa-clean":                {url:"$H/m/library/ess-data.html",Table:"ess-6-osa-clean",form_module:"ess-6-form-osa-clean",task_name:"6 Months - Epworth Sleepiness Scale (ESS)"},
        "ess-6-form-osa-clean":                {url:"$H/m/library/ess-form.html",Table:"ess-6-osa-clean",task_name:"6 Months - Epworth Sleepiness Scale (ESS)"},

        "date-24-data-osa-clean":                {url:"$H/m/library/date-data.html",Table:"date-24-osa-clean",form_module:"date-24-form-osa-clean",task_name:"24 Months - Visit Date"},
        "date-24-form-osa-clean":                {url:"$H/m/library/date-form.html",Table:"date-24-osa-clean",task_name:"24 Months - Visit Date"},
        "btb-24-data-osa-clean":                {url:"$H/m/library/btb-data.html",Table:"btb-24-osa-clean",form_module:"btb-24-form-osa-clean",task_name:"24 Months - Blood Test"},
        "btb-24-form-osa-clean":                {url:"$H/m/library/btb-form.html",Table:"btb-24-osa-clean",task_name:"24 Months - Blood Test"},
        "watchpat-24-data-osa-clean":                {url:"$H/m/library/watchpat-data.html",Table:"watchpat-24-osa-clean",form_module:"watchpat-24-form-osa-clean",task_name:"24 Months - WatchPat"},
        "watchpat-24-form-osa-clean":                {url:"$H/m/library/watchpat-form.html",Table:"watchpat-24-osa-clean",task_name:"24 Months - WatchPat"},
        "mri-24-data-osa-clean":                {url:"$H/m/library/mri-data.html",Table:"mri-24-osa-clean",form_module:"mri-24-form-osa-clean",task_name:"24 Months - MRI data"},
        "mri-24-form-osa-clean":                {url:"$H/m/library/mri-form.html",Table:"mri-24-osa-clean",task_name:"24 Months - MRI data"},
        "biomedical-measurements-24-data-osa-clean":                {url:"$H/m/library/biomedical-measurements-6-data.html",Table:"biomedical-measurements-24-osa-clean",form_module:"biomedical-measurements-24-form-osa-clean",task_name:"24 Months  - Biomedical Measurements"},
        "biomedical-measurements-24-form-osa-clean":                {url:"$H/m/library/biomedical-measurements-6-form.html",Table:"biomedical-measurements-24-osa-clean",task_name:"24 Months  - Biomedical Measurements"},
        "cirs-24-data-osa-clean":                {url:"$H/m/library/cirs-data.html",Table:"cirs-24-osa-clean",form_module:"cirs-24-form-osa-clean",task_name:"24 Months - Cumulative Illness Rating Scale"},
        "cirs-24-form-osa-clean":                {url:"$H/m/library/cirs-form.html",Table:"cirs-24-osa-clean",task_name:"24 Months - Cumulative Illness Rating Scale"},
        "ravlt-7-24-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-24-osa-clean",form_module:"ravlt-7-24-form-osa-clean",task_name:"24 Months - RAVLT Trials"},
        "ravlt-7-24-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-24-osa-clean",task_name:"24 Months - RAVLT Trials"},
        "trail-part-b-24-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-24-osa-clean",form_module:"trail-part-b-24-form-osa-clean",task_name:"24 Months - Trail Making Test Part A and B"},
        "trail-part-b-24-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-24-osa-clean",task_name:"24 Months - Trail Making Test Part A and B"},
        "dkefs-24-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-24-osa-clean",form_module:"dkefs-24-form-osa-clean",task_name:"24 Months - Delis Kaplan Executive Functioning System"},
        "dkefs-24-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-24-osa-clean",task_name:"24 Months - Delis Kaplan Executive Functioning System"},
        "sdmt-24-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-24-osa-clean",form_module:"sdmt-24-form-osa-clean",task_name:"24 Months - Symbol Digit Modalities Test"},
        "sdmt-24-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-24-osa-clean",task_name:"24 Months - Symbol Digit Modalities Test"},
        "cantab-24-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-24-osa-clean",form_module:"cantab-24-form-osa-clean",task_name:"24 Months - CANTAB"},
        "cantab-24-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-24-osa-clean",task_name:"24 Months - CANTAB"},
        "ravlt-7-de-24-data-osa-clean":                {url:"$H/m/library/ravlt-data.html",Table:"ravlt-de-24-osa-clean",form_module:"ravlt-7-de-24-form-osa-clean",task_name:"24 Months - Double Entry - RAVLT Trials"},
        "ravlt-7-de-24-form-osa-clean":                {url:"$H/m/library/ravlt-form.html",Table:"ravlt-de-24-osa-clean",task_name:"24 Months - Double Entry - RAVLT Trials"},
        "trail-part-b-de-24-data-osa-clean":                {url:"$H/m/library/trail-part-b-data.html",Table:"trail-part-b-de-24-osa-clean",form_module:"trail-part-b-de-24-form-osa-clean",task_name:"24 Months - Double Entry - Trail Making Test Part A and B"},
        "trail-part-b-de-24-form-osa-clean":                {url:"$H/m/library/trail-part-b-form.html",Table:"trail-part-b-de-24-osa-clean",task_name:"24 Months - Double Entry - Trail Making Test Part A and B"},
        "dkefs-de-24-data-osa-clean":                {url:"$H/m/library/dkefs-data.html",Table:"dkefs-de-24-osa-clean",form_module:"dkefs-de-24-form-osa-clean",task_name:"24 Months - Double Entry - Delis Kaplan Executive Functioning System"},
        "dkefs-de-24-form-osa-clean":                {url:"$H/m/library/dkefs-form.html",Table:"dkefs-de-24-osa-clean",task_name:"24 Months - Double Entry - Delis Kaplan Executive Functioning System"},
        "sdmt-de-24-data-osa-clean":                {url:"$H/m/library/sdmt-data.html",Table:"sdmt-de-24-osa-clean",form_module:"sdmt-de-24-form-osa-clean",task_name:"24 Months - Double Entry - Symbol Digit Modalities Test"},
        "sdmt-de-24-form-osa-clean":                {url:"$H/m/library/sdmt-form.html",Table:"sdmt-de-24-osa-clean",task_name:"24 Months - Double Entry - Symbol Digit Modalities Test"},
        "cantab-de-24-data-osa-clean":                {url:"$H/m/library/cantab-data.html",Table:"cantab-de-24-osa-clean",form_module:"cantab-de-24-form-osa-clean",task_name:"24 Months - Double Entry - CANTAB"},
        "cantab-de-24-form-osa-clean":                {url:"$H/m/library/cantab-form.html",Table:"cantab-de-24-osa-clean",task_name:"24 Months - Double Entry - CANTAB"},
        "phq-9-24-data-osa-clean":                {url:"$H/m/library/phq-data.html",Table:"phq-9-24-osa-clean",form_module:"phq-9-24-form-osa-clean",task_name:"24 Months - The Patient Health Questionnaire-9 (PHQ-9)"},
        "phq-9-24-form-osa-clean":                {url:"$H/m/library/phq-form.html",Table:"phq-9-24-osa-clean",task_name:"24 Months - The Patient Health Questionnaire-9 (PHQ-9)"},
        "bc-cci-24-data-osa-clean":                {url:"$H/m/library/bc-cci-data.html",Table:"bc-cci-24-osa-clean",form_module:"bc-cci-24-form-osa-clean",task_name:"24 Months - Brittish Colombia Cognitive Complaints Inventory"},
        "bc-cci-24-form-osa-clean":                {url:"$H/m/library/bc-cci-form.html",Table:"bc-cci-24-osa-clean",task_name:"24 Months - Brittish Colombia Cognitive Complaints Inventory"},
        "eq-5d-24-data-osa-clean":                {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-24-osa-clean",form_module:"eq-5d-24-form-osa-clean",task_name:"24 Months - Quality of life inventory (EQ-5D-5L)"},
        "eq-5d-24-form-osa-clean":                {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-24-osa-clean",task_name:"24 Months - Quality of life inventory (EQ-5D-5L)"},
        "ess-24-data-osa-clean":                {url:"$H/m/library/ess-data.html",Table:"ess-24-osa-clean",form_module:"ess-24-form-osa-clean",task_name:"24 Months - Epworth Sleepiness Scale (ESS)"},
        "ess-24-form-osa-clean":                {url:"$H/m/library/ess-form.html",Table:"ess-24-osa-clean",task_name:"24 Months - Epworth Sleepiness Scale (ESS)"},

        "treatment-1-data-osa-clean":                {url:"$H/m/library/treatment-1-data.html",Table:"treatment-1-osa-clean",form_module:"treatment-1-form-osa-clean",task_name:"Treatment Visit - First Treatment Visit"},
        "treatment-1-form-osa-clean":                {url:"$H/m/library/treatment-1-form.html",Table:"treatment-1-osa-clean",task_name:"Treatment Visit - First Treatment Visit"},
        "treatment-fu-data-osa-clean":                {url:"$H/m/library/treatment-fu-data.html",Table:"treatment-fu-osa-clean",form_module:"treatment-fu-form-osa-clean",task_name:"Treatment Visit - Treatment visit follow-up"},
        "treatment-fu-form-osa-clean":                {url:"$H/m/library/treatment-fu-form.html",Table:"treatment-fu-osa-clean",task_name:"Treatment Visit - Treatment visit follow-up"},

    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    //if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
            $vm.module_list[p].Table2="demo-"+$vm.module_list[p].Table2;
            $vm.module_list[p].Table3="demo-"+$vm.module_list[p].Table3;
        }
    //}

})();
